server:
  port: 5001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCL21PDB1
    username: airline_user_db
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
minio:
  enabled: true
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: 12345678
  bucket: avatars
  presign-expiration: 7 #day

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"