server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:1521/ORCL21PDB1
    username: airline_user_db
    password: ${USER_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

minio:
  enabled: true
  endpoint: http://minio:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: avatars
  presign-expiration: 7

eureka:
  instance:
    prefer-ip-address: false
    hostname: user-service

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/