server:
  port: 5002

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCL21PDB1
    username: airline_auth_db
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
