server:
  port: 5003

spring:
  application:
    name: notification-service

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: your-email.gmail.com
    password: your-password
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  logging:
    level:
      root: info


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
